services:
  - type: web
    name: style-transfer-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --worker-class sync --threads 4 --timeout 120"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    plan: free
